### ISSUE TITLE
direcotory tree for 'npm install zclip'

### ISSUE THREAD

**Issue by yz101-osrm** [SiliconLabs/zclip.js#1]
I tried to implement this zclip.js on the Thread border router kit from SiLabs, and further zclip-rd on the BR. I am a newbie using npm and nodejs, and I ran into a mess of confusion where and how to install this zclip.js. 
if I $git clone zclip.js, inside this folder $npm install zclip, gives ERR! Refusing to install zclip as a dependency of itself. 
else if I just $npm install zclip in another new empty directory, node_modules are created inside which is a zclip (not zclip.js) subfolder. Navigate into zclip, run $npm test, ERR! jest: not found. I know I need to $npm install jest. So here is another question, in which directory should I install jest?
The $npm install to a 'local' directory is a mystery to me. Can you show me an example of working directory tree? Thanks.

**Comment by prestonfick** [comment]
I believe you should either install run the `npm install zclip`, which should apply all package dependencies for you. The alternative is to clone this repo, but in the zclip.js directory run `npm install` to get the package dependencies. All dependencies should exist within the node_modules folder.
